// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AnyConnectionRulePart any connection rule part
// swagger:model AnyConnectionRulePart
type AnyConnectionRulePart struct {
}

// ConnectionRulePartType gets the connection rule part type of this subtype
func (m *AnyConnectionRulePart) ConnectionRulePartType() string {
	return "AnyConnectionRulePart"
}

// SetConnectionRulePartType sets the connection rule part type of this subtype
func (m *AnyConnectionRulePart) SetConnectionRulePartType(val string) {

}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *AnyConnectionRulePart) UnmarshalJSON(raw []byte) error {
	var data struct {
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		ConnectionRulePartType string `json:"connectionRulePartType"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result AnyConnectionRulePart

	if base.ConnectionRulePartType != result.ConnectionRulePartType() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid connectionRulePartType value: %q", base.ConnectionRulePartType)
	}

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m AnyConnectionRulePart) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {
	}{},
	)
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		ConnectionRulePartType string `json:"connectionRulePartType"`
	}{

		ConnectionRulePartType: m.ConnectionRulePartType(),
	},
	)
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this any connection rule part
func (m *AnyConnectionRulePart) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *AnyConnectionRulePart) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AnyConnectionRulePart) UnmarshalBinary(b []byte) error {
	var res AnyConnectionRulePart
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
