package model

// Code generated by go-swagger; DO NOT EDIT.

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"io"
	"net/http"
	"time"
)

// NewGetKubernetesClustersKubernetesClusterIDParams creates a new GetKubernetesClustersKubernetesClusterIDParams object
// with the default values initialized.
func NewGetKubernetesClustersKubernetesClusterIDParams() *GetKubernetesClustersKubernetesClusterIDParams {
	var ()
	return &GetKubernetesClustersKubernetesClusterIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetKubernetesClustersKubernetesClusterIDParamsWithTimeout creates a new GetKubernetesClustersKubernetesClusterIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetKubernetesClustersKubernetesClusterIDParamsWithTimeout(timeout time.Duration) *GetKubernetesClustersKubernetesClusterIDParams {
	var ()
	return &GetKubernetesClustersKubernetesClusterIDParams{

		timeout: timeout,
	}
}

// NewGetKubernetesClustersKubernetesClusterIDParamsWithContext creates a new GetKubernetesClustersKubernetesClusterIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetKubernetesClustersKubernetesClusterIDParamsWithContext(ctx context.Context) *GetKubernetesClustersKubernetesClusterIDParams {
	var ()
	return &GetKubernetesClustersKubernetesClusterIDParams{

		Context: ctx,
	}
}

// NewGetKubernetesClustersKubernetesClusterIDParamsWithHTTPClient creates a new GetKubernetesClustersKubernetesClusterIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetKubernetesClustersKubernetesClusterIDParamsWithHTTPClient(client *http.Client) *GetKubernetesClustersKubernetesClusterIDParams {
	var ()
	return &GetKubernetesClustersKubernetesClusterIDParams{
		HTTPClient: client,
	}
}

type GetKubernetesClustersKubernetesClusterIDParams struct {

	/*KubernetesClusterID
	  SecureCN Kubernetes cluster ID

	*/
	KubernetesClusterID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get kubernetes clusters kubernetes cluster ID params
func (o *GetKubernetesClustersKubernetesClusterIDParams) WithTimeout(timeout time.Duration) *GetKubernetesClustersKubernetesClusterIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get kubernetes clusters kubernetes cluster ID params
func (o *GetKubernetesClustersKubernetesClusterIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get kubernetes clusters kubernetes cluster ID params
func (o *GetKubernetesClustersKubernetesClusterIDParams) WithContext(ctx context.Context) *GetKubernetesClustersKubernetesClusterIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get kubernetes clusters kubernetes cluster ID params
func (o *GetKubernetesClustersKubernetesClusterIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get kubernetes clusters kubernetes cluster ID params
func (o *GetKubernetesClustersKubernetesClusterIDParams) WithHTTPClient(client *http.Client) *GetKubernetesClustersKubernetesClusterIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get kubernetes clusters kubernetes cluster ID params
func (o *GetKubernetesClustersKubernetesClusterIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKubernetesClusterID adds the kubernetesClusterID to the get kubernetes clusters kubernetes cluster ID params
func (o *GetKubernetesClustersKubernetesClusterIDParams) WithKubernetesClusterID(kubernetesClusterID strfmt.UUID) *GetKubernetesClustersKubernetesClusterIDParams {
	o.SetKubernetesClusterID(kubernetesClusterID)
	return o
}

// SetKubernetesClusterID adds the kubernetesClusterId to the get kubernetes clusters kubernetes cluster ID params
func (o *GetKubernetesClustersKubernetesClusterIDParams) SetKubernetesClusterID(kubernetesClusterID strfmt.UUID) {
	o.KubernetesClusterID = kubernetesClusterID
}

// WriteToRequest writes these params to a swagger request
func (o *GetKubernetesClustersKubernetesClusterIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param kubernetesClusterId
	if err := r.SetPathParam("kubernetesClusterId", o.KubernetesClusterID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

type GetKubernetesClustersKubernetesClusterIDReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKubernetesClustersKubernetesClusterIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetKubernetesClustersKubernetesClusterIDOK()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetKubernetesClustersKubernetesClusterIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetKubernetesClustersKubernetesClusterIDCreated creates a GetKubernetesClustersKubernetesClusterIDCreated with default headers values
func NewGetKubernetesClustersKubernetesClusterIDCreated() *GetKubernetesClustersKubernetesClusterIDCreated {
	return &GetKubernetesClustersKubernetesClusterIDCreated{}
}

/*GetKubernetesClustersKubernetesClusterIDCreated handles this case with default header values.

Agent was added.
*/

const GetKubernetesClustersKubernetesClusterIDCreatedCode int = 201

func NewGetKubernetesClustersKubernetesClusterIDOK() *GetKubernetesClustersKubernetesClusterIDOK {
	return &GetKubernetesClustersKubernetesClusterIDOK{}
}

type GetKubernetesClustersKubernetesClusterIDOK struct {
	Payload *KubernetesCluster
}

func (o *GetKubernetesClustersKubernetesClusterIDOK) Error() string {
	return fmt.Sprintf("[GET /kubernetesClusters/{kubernetesClusterId}][%d] getKubernetesClustersKubernetesClusterIdOK  %+v", 200, o.Payload)
}

func (o *GetKubernetesClustersKubernetesClusterIDOK) GetPayload() *KubernetesCluster {
	return o.Payload
}

func (o *GetKubernetesClustersKubernetesClusterIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(KubernetesCluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

type GetKubernetesClustersKubernetesClusterIDCreated struct {
	Payload *KubernetesCluster
}

func (o *GetKubernetesClustersKubernetesClusterIDCreated) Error() string {
	return fmt.Sprintf("[GET /kubernetesClusters/{kubernetesClusterId}][%d] getKubernetesClustersKubernetesClusterIdCreated  %+v", 201, o.Payload)
}

func (o *GetKubernetesClustersKubernetesClusterIDCreated) GetPayload() *KubernetesCluster {
	return o.Payload
}

func (o *GetKubernetesClustersKubernetesClusterIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(KubernetesCluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// WithPayload adds the payload to the get kubernetes clusters kubernetes cluster Id created response
func (o *GetKubernetesClustersKubernetesClusterIDCreated) WithPayload(payload *KubernetesCluster) *GetKubernetesClustersKubernetesClusterIDCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get kubernetes clusters kubernetes cluster Id created response
func (o *GetKubernetesClustersKubernetesClusterIDCreated) SetPayload(payload *KubernetesCluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetKubernetesClustersKubernetesClusterIDCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetKubernetesClustersKubernetesClusterIDDefault unknown error

swagger:response getKubernetesClustersKubernetesClusterIdDefault
*/
type GetKubernetesClustersKubernetesClusterIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *APIResponse `json:"body,omitempty"`
}

// NewGetKubernetesClustersKubernetesClusterIDDefault creates GetKubernetesClustersKubernetesClusterIDDefault with default headers values
func NewGetKubernetesClustersKubernetesClusterIDDefault(code int) *GetKubernetesClustersKubernetesClusterIDDefault {
	return &GetKubernetesClustersKubernetesClusterIDDefault{
		_statusCode: code,
	}
}

// Code gets the status code for the get kubernetes clusters kubernetes cluster ID default response
func (o *GetKubernetesClustersKubernetesClusterIDDefault) Code() int {
	return o._statusCode
}

func (o *GetKubernetesClustersKubernetesClusterIDDefault) Error() string {
	return fmt.Sprintf("[GET /kubernetesClusters/{kubernetesClusterId}][%d] GetKubernetesClustersKubernetesClusterID default  %+v", o._statusCode, o.Payload)
}

func (o *GetKubernetesClustersKubernetesClusterIDDefault) GetPayload() *APIResponse {
	return o.Payload
}

func (o *GetKubernetesClustersKubernetesClusterIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
