// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// AppRuleType app rule type
// swagger:model AppRuleType
type AppRuleType string

const (

	// AppRuleTypeALLOW captures enum value "ALLOW"
	AppRuleTypeALLOW AppRuleType = "ALLOW"

	// AppRuleTypeDETECT captures enum value "DETECT"
	AppRuleTypeDETECT AppRuleType = "DETECT"

	// AppRuleTypeBLOCK captures enum value "BLOCK"
	AppRuleTypeBLOCK AppRuleType = "BLOCK"
)

// for schema
var appRuleTypeEnum []interface{}

func init() {
	var res []AppRuleType
	if err := json.Unmarshal([]byte(`["ALLOW","DETECT","BLOCK"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		appRuleTypeEnum = append(appRuleTypeEnum, v)
	}
}

func (m AppRuleType) validateAppRuleTypeEnum(path, location string, value AppRuleType) error {
	if err := validate.Enum(path, location, value, appRuleTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this app rule type
func (m AppRuleType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAppRuleTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
