// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteCdRuleIDDeploymentRuleReader is a Reader for the DeleteCdRuleIDDeploymentRule structure.
type DeleteCdRuleIDDeploymentRuleReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCdRuleIDDeploymentRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteCdRuleIDDeploymentRuleNoContent()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCdRuleIDDeploymentRuleNoContent creates a DeleteCdRuleIDDeploymentRuleNoContent with default headers values
func NewDeleteCdRuleIDDeploymentRuleNoContent() *DeleteCdRuleIDDeploymentRuleNoContent {
	return &DeleteCdRuleIDDeploymentRuleNoContent{}
}

/*DeleteCdRuleIDDeploymentRuleNoContent handles this case with default header values.

deleted
*/
type DeleteCdRuleIDDeploymentRuleNoContent struct {
}

func (o *DeleteCdRuleIDDeploymentRuleNoContent) Error() string {
	return fmt.Sprintf("[DELETE /cd/{ruleId}/deploymentRule][%d] deleteCdRuleIdDeploymentRuleNoContent ", 204)
}

func (o *DeleteCdRuleIDDeploymentRuleNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
