// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCiPolicyPolicyIDParams creates a new DeleteCiPolicyPolicyIDParams object
// with the default values initialized.
func NewDeleteCiPolicyPolicyIDParams() *DeleteCiPolicyPolicyIDParams {
	var ()
	return &DeleteCiPolicyPolicyIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCiPolicyPolicyIDParamsWithTimeout creates a new DeleteCiPolicyPolicyIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCiPolicyPolicyIDParamsWithTimeout(timeout time.Duration) *DeleteCiPolicyPolicyIDParams {
	var ()
	return &DeleteCiPolicyPolicyIDParams{

		timeout: timeout,
	}
}

// NewDeleteCiPolicyPolicyIDParamsWithContext creates a new DeleteCiPolicyPolicyIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCiPolicyPolicyIDParamsWithContext(ctx context.Context) *DeleteCiPolicyPolicyIDParams {
	var ()
	return &DeleteCiPolicyPolicyIDParams{

		Context: ctx,
	}
}

// NewDeleteCiPolicyPolicyIDParamsWithHTTPClient creates a new DeleteCiPolicyPolicyIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCiPolicyPolicyIDParamsWithHTTPClient(client *http.Client) *DeleteCiPolicyPolicyIDParams {
	var ()
	return &DeleteCiPolicyPolicyIDParams{
		HTTPClient: client,
	}
}

/*DeleteCiPolicyPolicyIDParams contains all the parameters to send to the API endpoint
for the delete ci policy policy ID operation typically these are written to a http.Request
*/
type DeleteCiPolicyPolicyIDParams struct {

	/*PolicyID*/
	PolicyID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete ci policy policy ID params
func (o *DeleteCiPolicyPolicyIDParams) WithTimeout(timeout time.Duration) *DeleteCiPolicyPolicyIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete ci policy policy ID params
func (o *DeleteCiPolicyPolicyIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete ci policy policy ID params
func (o *DeleteCiPolicyPolicyIDParams) WithContext(ctx context.Context) *DeleteCiPolicyPolicyIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete ci policy policy ID params
func (o *DeleteCiPolicyPolicyIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete ci policy policy ID params
func (o *DeleteCiPolicyPolicyIDParams) WithHTTPClient(client *http.Client) *DeleteCiPolicyPolicyIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete ci policy policy ID params
func (o *DeleteCiPolicyPolicyIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPolicyID adds the policyID to the delete ci policy policy ID params
func (o *DeleteCiPolicyPolicyIDParams) WithPolicyID(policyID strfmt.UUID) *DeleteCiPolicyPolicyIDParams {
	o.SetPolicyID(policyID)
	return o
}

// SetPolicyID adds the policyId to the delete ci policy policy ID params
func (o *DeleteCiPolicyPolicyIDParams) SetPolicyID(policyID strfmt.UUID) {
	o.PolicyID = policyID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCiPolicyPolicyIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param policyId
	if err := r.SetPathParam("policyId", o.PolicyID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
