// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetKubernetesClustersKubernetesClusterNameReader is a Reader for the GetKubernetesClustersKubernetesClusterName structure.
type GetKubernetesClustersKubernetesClusterNameReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKubernetesClustersKubernetesClusterNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetKubernetesClustersKubernetesClusterNameOK()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetKubernetesClustersKubernetesClusterNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetKubernetesClustersKubernetesClusterNameOK creates a GetKubernetesClustersKubernetesClusterNameOK with default headers values
func NewGetKubernetesClustersKubernetesClusterNameOK() *GetKubernetesClustersKubernetesClusterNameOK {
	return &GetKubernetesClustersKubernetesClusterNameOK{}
}

/*GetKubernetesClustersKubernetesClusterNameOK handles this case with default header values.

Success
*/
type GetKubernetesClustersKubernetesClusterNameOK struct {
	Payload strfmt.UUID
}

func (o *GetKubernetesClustersKubernetesClusterNameOK) Error() string {
	return fmt.Sprintf("[GET /kubernetesClusters/{kubernetesClusterName}][%d] getKubernetesClustersKubernetesClusterNameOK  %+v", 200, o.Payload)
}

func (o *GetKubernetesClustersKubernetesClusterNameOK) GetPayload() strfmt.UUID {
	return o.Payload
}

func (o *GetKubernetesClustersKubernetesClusterNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetKubernetesClustersKubernetesClusterNameDefault creates a GetKubernetesClustersKubernetesClusterNameDefault with default headers values
func NewGetKubernetesClustersKubernetesClusterNameDefault(code int) *GetKubernetesClustersKubernetesClusterNameDefault {
	return &GetKubernetesClustersKubernetesClusterNameDefault{
		_statusCode: code,
	}
}

/*GetKubernetesClustersKubernetesClusterNameDefault handles this case with default header values.

unknown error
*/
type GetKubernetesClustersKubernetesClusterNameDefault struct {
	_statusCode int

	Payload *APIResponse
}

// Code gets the status code for the get kubernetes clusters kubernetes cluster name default response
func (o *GetKubernetesClustersKubernetesClusterNameDefault) Code() int {
	return o._statusCode
}

func (o *GetKubernetesClustersKubernetesClusterNameDefault) Error() string {
	return fmt.Sprintf("[GET /kubernetesClusters/{kubernetesClusterName}][%d] GetKubernetesClustersKubernetesClusterName default  %+v", o._statusCode, o.Payload)
}

func (o *GetKubernetesClustersKubernetesClusterNameDefault) GetPayload() *APIResponse {
	return o.Payload
}

func (o *GetKubernetesClustersKubernetesClusterNameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
