// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetDeployersReader is a Reader for the GetDeployers structure.
type GetDeployersReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeployersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeployersOK()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDeployersOK creates a GetDeployersOK with default headers values
func NewGetDeployersOK() *GetDeployersOK {
	return &GetDeployersOK{}
}

/*GetDeployersOK handles this case with default header values.

Success
*/
type GetDeployersOK struct {
	Payload []Deployer
}

func (o *GetDeployersOK) Error() string {
	return fmt.Sprintf("[GET /deployers][%d] getDeployersOK  %+v", 200, o.Payload)
}

func (o *GetDeployersOK) GetPayload() []Deployer {
	return o.Payload
}

func (o *GetDeployersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload as interface type
	payload, err := UnmarshalDeployerSlice(response.Body(), consumer)
	if err != nil {
		return err
	}
	o.Payload = payload

	return nil
}
