// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCdRuleIDDeploymentRuleParams creates a new GetCdRuleIDDeploymentRuleParams object
// with the default values initialized.
func NewGetCdRuleIDDeploymentRuleParams() *GetCdRuleIDDeploymentRuleParams {
	var ()
	return &GetCdRuleIDDeploymentRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCdRuleIDDeploymentRuleParamsWithTimeout creates a new GetCdRuleIDDeploymentRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCdRuleIDDeploymentRuleParamsWithTimeout(timeout time.Duration) *GetCdRuleIDDeploymentRuleParams {
	var ()
	return &GetCdRuleIDDeploymentRuleParams{

		timeout: timeout,
	}
}

// NewGetCdRuleIDDeploymentRuleParamsWithContext creates a new GetCdRuleIDDeploymentRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCdRuleIDDeploymentRuleParamsWithContext(ctx context.Context) *GetCdRuleIDDeploymentRuleParams {
	var ()
	return &GetCdRuleIDDeploymentRuleParams{

		Context: ctx,
	}
}

// NewGetCdRuleIDDeploymentRuleParamsWithHTTPClient creates a new GetCdRuleIDDeploymentRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCdRuleIDDeploymentRuleParamsWithHTTPClient(client *http.Client) *GetCdRuleIDDeploymentRuleParams {
	var ()
	return &GetCdRuleIDDeploymentRuleParams{
		HTTPClient: client,
	}
}

/*GetCdRuleIDDeploymentRuleParams contains all the parameters to send to the API endpoint
for the get cd rule ID deployment rule operation typically these are written to a http.Request
*/
type GetCdRuleIDDeploymentRuleParams struct {

	/*RuleID
	  ruleId (uid)

	*/
	RuleID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cd rule ID deployment rule params
func (o *GetCdRuleIDDeploymentRuleParams) WithTimeout(timeout time.Duration) *GetCdRuleIDDeploymentRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cd rule ID deployment rule params
func (o *GetCdRuleIDDeploymentRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cd rule ID deployment rule params
func (o *GetCdRuleIDDeploymentRuleParams) WithContext(ctx context.Context) *GetCdRuleIDDeploymentRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cd rule ID deployment rule params
func (o *GetCdRuleIDDeploymentRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cd rule ID deployment rule params
func (o *GetCdRuleIDDeploymentRuleParams) WithHTTPClient(client *http.Client) *GetCdRuleIDDeploymentRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cd rule ID deployment rule params
func (o *GetCdRuleIDDeploymentRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRuleID adds the ruleID to the get cd rule ID deployment rule params
func (o *GetCdRuleIDDeploymentRuleParams) WithRuleID(ruleID strfmt.UUID) *GetCdRuleIDDeploymentRuleParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the get cd rule ID deployment rule params
func (o *GetCdRuleIDDeploymentRuleParams) SetRuleID(ruleID strfmt.UUID) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCdRuleIDDeploymentRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ruleId
	if err := r.SetPathParam("ruleId", o.RuleID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
