// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IPRangeConnectionRulePart Ip range connection rule part
// swagger:model IpRangeConnectionRulePart
type IPRangeConnectionRulePart struct {

	// networks
	Networks []string `json:"networks"`
}

// ConnectionRulePartType gets the connection rule part type of this subtype
func (m *IPRangeConnectionRulePart) ConnectionRulePartType() string {
	return "IpRangeConnectionRulePart"
}

// SetConnectionRulePartType sets the connection rule part type of this subtype
func (m *IPRangeConnectionRulePart) SetConnectionRulePartType(val string) {

}

// Networks gets the networks of this subtype

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *IPRangeConnectionRulePart) UnmarshalJSON(raw []byte) error {
	var data struct {

		// networks
		Networks []string `json:"networks"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		ConnectionRulePartType string `json:"connectionRulePartType"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result IPRangeConnectionRulePart

	if base.ConnectionRulePartType != result.ConnectionRulePartType() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid connectionRulePartType value: %q", base.ConnectionRulePartType)
	}

	result.Networks = data.Networks

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m IPRangeConnectionRulePart) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// networks
		Networks []string `json:"networks"`
	}{

		Networks: m.Networks,
	},
	)
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		ConnectionRulePartType string `json:"connectionRulePartType"`
	}{

		ConnectionRulePartType: m.ConnectionRulePartType(),
	},
	)
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this Ip range connection rule part
func (m *IPRangeConnectionRulePart) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *IPRangeConnectionRulePart) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPRangeConnectionRulePart) UnmarshalBinary(b []byte) error {
	var res IPRangeConnectionRulePart
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
