// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PodAnyConnectionRulePart pod any connection rule part
// swagger:model PodAnyConnectionRulePart
type PodAnyConnectionRulePart struct {

	// environments
	Environments []string `json:"environments"`

	// vulnerability
	VulnerabilitySeverityLevel string `json:"vulnerabilitySeverityLevel,omitempty"`
}

// ConnectionRulePartType gets the connection rule part type of this subtype
func (m *PodAnyConnectionRulePart) ConnectionRulePartType() string {
	return "PodAnyConnectionRulePart"
}

// SetConnectionRulePartType sets the connection rule part type of this subtype
func (m *PodAnyConnectionRulePart) SetConnectionRulePartType(val string) {

}

// Environments gets the environments of this subtype

// Vulnerability gets the vulnerability of this subtype

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *PodAnyConnectionRulePart) UnmarshalJSON(raw []byte) error {
	var data struct {

		// environments
		Environments []string `json:"environments"`

		// vulnerability
		Vulnerability string `json:"vulnerabilitySeverityLevel,omitempty"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		ConnectionRulePartType string `json:"connectionRulePartType"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result PodAnyConnectionRulePart

	if base.ConnectionRulePartType != result.ConnectionRulePartType() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid connectionRulePartType value: %q", base.ConnectionRulePartType)
	}

	result.Environments = data.Environments

	result.VulnerabilitySeverityLevel = data.Vulnerability

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m PodAnyConnectionRulePart) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// environments
		Environments []string `json:"environments"`

		// vulnerability
		Vulnerability string `json:"vulnerabilitySeverityLevel,omitempty"`
	}{

		Environments: m.Environments,

		Vulnerability: m.VulnerabilitySeverityLevel,
	},
	)
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		ConnectionRulePartType string `json:"connectionRulePartType"`
	}{

		ConnectionRulePartType: m.ConnectionRulePartType(),
	},
	)
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this pod any connection rule part
func (m *PodAnyConnectionRulePart) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVulnerability(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PodAnyConnectionRulePart) validateVulnerability(formats strfmt.Registry) error {

	if swag.IsZero(m.VulnerabilitySeverityLevel) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PodAnyConnectionRulePart) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PodAnyConnectionRulePart) UnmarshalBinary(b []byte) error {
	var res PodAnyConnectionRulePart
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
