// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostEnvironmentsReader is a Reader for the PostEnvironments structure.
type PostEnvironmentsReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostEnvironmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostEnvironmentsCreated()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostEnvironmentsUnauthorized()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostEnvironmentsCreated creates a PostEnvironmentsCreated with default headers values
func NewPostEnvironmentsCreated() *PostEnvironmentsCreated {
	return &PostEnvironmentsCreated{}
}

/*PostEnvironmentsCreated handles this case with default header values.

Added
*/
type PostEnvironmentsCreated struct {
	Payload *Environment
}

func (o *PostEnvironmentsCreated) Error() string {
	return fmt.Sprintf("[POST /environments][%d] postEnvironmentsCreated  %+v", 201, o.Payload)
}

func (o *PostEnvironmentsCreated) GetPayload() *Environment {
	return o.Payload
}

func (o *PostEnvironmentsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(Environment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostEnvironmentsUnauthorized creates a PostEnvironmentsUnauthorized with default headers values
func NewPostEnvironmentsUnauthorized() *PostEnvironmentsUnauthorized {
	return &PostEnvironmentsUnauthorized{}
}

/*PostEnvironmentsUnauthorized handles this case with default header values.

Unauthorized.
*/
type PostEnvironmentsUnauthorized struct {
}

func (o *PostEnvironmentsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /environments][%d] postEnvironmentsUnauthorized ", 401)
}

func (o *PostEnvironmentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
