// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutCdRuleIDConnectionsRuleParams creates a new PutCdRuleIDConnectionsRuleParams object
// with the default values initialized.
func NewPutCdRuleIDConnectionsRuleParams() *PutCdRuleIDConnectionsRuleParams {
	var ()
	return &PutCdRuleIDConnectionsRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutCdRuleIDConnectionsRuleParamsWithTimeout creates a new PutCdRuleIDConnectionsRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutCdRuleIDConnectionsRuleParamsWithTimeout(timeout time.Duration) *PutCdRuleIDConnectionsRuleParams {
	var ()
	return &PutCdRuleIDConnectionsRuleParams{

		timeout: timeout,
	}
}

// NewPutCdRuleIDConnectionsRuleParamsWithContext creates a new PutCdRuleIDConnectionsRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutCdRuleIDConnectionsRuleParamsWithContext(ctx context.Context) *PutCdRuleIDConnectionsRuleParams {
	var ()
	return &PutCdRuleIDConnectionsRuleParams{

		Context: ctx,
	}
}

// NewPutCdRuleIDConnectionsRuleParamsWithHTTPClient creates a new PutCdRuleIDConnectionsRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutCdRuleIDConnectionsRuleParamsWithHTTPClient(client *http.Client) *PutCdRuleIDConnectionsRuleParams {
	var ()
	return &PutCdRuleIDConnectionsRuleParams{
		HTTPClient: client,
	}
}

/*PutCdRuleIDConnectionsRuleParams contains all the parameters to send to the API endpoint
for the put cd rule ID connections rule operation typically these are written to a http.Request
*/
type PutCdRuleIDConnectionsRuleParams struct {

	/*Body*/
	Body *CdConnectionRule
	/*RuleID
	  ruleId (uid)

	*/
	RuleID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put cd rule ID connections rule params
func (o *PutCdRuleIDConnectionsRuleParams) WithTimeout(timeout time.Duration) *PutCdRuleIDConnectionsRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put cd rule ID connections rule params
func (o *PutCdRuleIDConnectionsRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put cd rule ID connections rule params
func (o *PutCdRuleIDConnectionsRuleParams) WithContext(ctx context.Context) *PutCdRuleIDConnectionsRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put cd rule ID connections rule params
func (o *PutCdRuleIDConnectionsRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put cd rule ID connections rule params
func (o *PutCdRuleIDConnectionsRuleParams) WithHTTPClient(client *http.Client) *PutCdRuleIDConnectionsRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put cd rule ID connections rule params
func (o *PutCdRuleIDConnectionsRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put cd rule ID connections rule params
func (o *PutCdRuleIDConnectionsRuleParams) WithBody(body CdConnectionRule) *PutCdRuleIDConnectionsRuleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put cd rule ID connections rule params
func (o *PutCdRuleIDConnectionsRuleParams) SetBody(body CdConnectionRule) {
	o.Body = &body
}

// WithRuleID adds the ruleID to the put cd rule ID connections rule params
func (o *PutCdRuleIDConnectionsRuleParams) WithRuleID(ruleID strfmt.UUID) *PutCdRuleIDConnectionsRuleParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the put cd rule ID connections rule params
func (o *PutCdRuleIDConnectionsRuleParams) SetRuleID(ruleID strfmt.UUID) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *PutCdRuleIDConnectionsRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param ruleId
	if err := r.SetPathParam("ruleId", o.RuleID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
