// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutDeployersDeployerIDReader is a Reader for the PutDeployersDeployerID structure.
type PutDeployersDeployerIDReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutDeployersDeployerIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutDeployersDeployerIDOK()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutDeployersDeployerIDOK creates a PutDeployersDeployerIDOK with default headers values
func NewPutDeployersDeployerIDOK() *PutDeployersDeployerIDOK {
	return &PutDeployersDeployerIDOK{}
}

/*PutDeployersDeployerIDOK handles this case with default header values.

Success
*/
type PutDeployersDeployerIDOK struct {
	Payload Deployer
}

func (o *PutDeployersDeployerIDOK) Error() string {
	return fmt.Sprintf("[PUT /deployers/{deployerId}][%d] putDeployersDeployerIdOK  %+v", 200, o.Payload)
}

func (o *PutDeployersDeployerIDOK) GetPayload() Deployer {
	return o.Payload
}

func (o *PutDeployersDeployerIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload as interface type
	payload, err := UnmarshalDeployer(response.Body(), consumer)
	if err != nil {
		return err
	}
	o.Payload = payload

	return nil
}
