// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
)

// NewPutCdPolicyPolicyIDParams creates a new PutCdPolicyPolicyIDParams object
// with the default values initialized.
func NewPutCdPolicyPolicyIDParams() *PutCdPolicyPolicyIDParams {
	var ()
	return &PutCdPolicyPolicyIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutCdPolicyPolicyIDParamsWithTimeout creates a new PutCdPolicyPolicyIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutCdPolicyPolicyIDParamsWithTimeout(timeout time.Duration) *PutCdPolicyPolicyIDParams {
	var ()
	return &PutCdPolicyPolicyIDParams{

		timeout: timeout,
	}
}

// NewPutCdPolicyPolicyIDParamsWithContext creates a new PutCdPolicyPolicyIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutCdPolicyPolicyIDParamsWithContext(ctx context.Context) *PutCdPolicyPolicyIDParams {
	var ()
	return &PutCdPolicyPolicyIDParams{

		Context: ctx,
	}
}

// NewPutCdPolicyPolicyIDParamsWithHTTPClient creates a new PutCdPolicyPolicyIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutCdPolicyPolicyIDParamsWithHTTPClient(client *http.Client) *PutCdPolicyPolicyIDParams {
	var ()
	return &PutCdPolicyPolicyIDParams{
		HTTPClient: client,
	}
}

/*PutCdPolicyPolicyIDParams contains all the parameters to send to the API endpoint
for the put cd policy policy ID operation typically these are written to a http.Request
*/
type PutCdPolicyPolicyIDParams struct {

	/*Body*/
	Body *CdPolicy
	/*PolicyID*/
	PolicyID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put cd policy policy ID params
func (o *PutCdPolicyPolicyIDParams) WithTimeout(timeout time.Duration) *PutCdPolicyPolicyIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put cd policy policy ID params
func (o *PutCdPolicyPolicyIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put cd policy policy ID params
func (o *PutCdPolicyPolicyIDParams) WithContext(ctx context.Context) *PutCdPolicyPolicyIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put cd policy policy ID params
func (o *PutCdPolicyPolicyIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put cd policy policy ID params
func (o *PutCdPolicyPolicyIDParams) WithHTTPClient(client *http.Client) *PutCdPolicyPolicyIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put cd policy policy ID params
func (o *PutCdPolicyPolicyIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put cd policy policy ID params
func (o *PutCdPolicyPolicyIDParams) WithBody(body *CdPolicy) *PutCdPolicyPolicyIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put cd policy policy ID params
func (o *PutCdPolicyPolicyIDParams) SetBody(body *CdPolicy) {
	o.Body = body
}

// WithPolicyID adds the policyID to the put cd policy policy ID params
func (o *PutCdPolicyPolicyIDParams) WithPolicyID(policyID strfmt.UUID) *PutCdPolicyPolicyIDParams {
	o.SetPolicyID(policyID)
	return o
}

// SetPolicyID adds the policyId to the put cd policy policy ID params
func (o *PutCdPolicyPolicyIDParams) SetPolicyID(policyID strfmt.UUID) {
	o.PolicyID = policyID
}

// WriteToRequest writes these params to a swagger request
func (o *PutCdPolicyPolicyIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param policyId
	if err := r.SetPathParam("policyId", o.PolicyID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
