// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// Risk risk
// swagger:model Risk
type Risk string

const (

	// RiskNORISK captures enum value "NO_RISK"
	RiskNORISK Risk = "NO_RISK"

	// RiskMEDIUM captures enum value "MEDIUM"
	RiskMEDIUM Risk = "MEDIUM"

	// RiskHIGH captures enum value "HIGH"
	RiskHIGH Risk = "HIGH"
)

// for schema
var riskEnum []interface{}

func init() {
	var res []Risk
	if err := json.Unmarshal([]byte(`["NO_RISK","MEDIUM","HIGH"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		riskEnum = append(riskEnum, v)
	}
}

func (m Risk) validateRiskEnum(path, location string, value Risk) error {
	if err := validate.Enum(path, location, value, riskEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this risk
func (m Risk) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateRiskEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
