// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// AppRuleStatus app rule status
// swagger:model AppRuleStatus
type AppRuleStatus string

const (

	// AppRuleStatusENABLED captures enum value "ENABLED"
	AppRuleStatusENABLED AppRuleStatus = "ENABLED"

	// AppRuleStatusDISABLED captures enum value "DISABLED"
	AppRuleStatusDISABLED AppRuleStatus = "DISABLED"
)

// for schema
var appRuleStatusEnum []interface{}

func init() {
	var res []AppRuleStatus
	if err := json.Unmarshal([]byte(`["ENABLED","DISABLED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		appRuleStatusEnum = append(appRuleStatusEnum, v)
	}
}

func (m AppRuleStatus) validateAppRuleStatusEnum(path, location string, value AppRuleStatus) error {
	if err := validate.Enum(path, location, value, appRuleStatusEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this app rule status
func (m AppRuleStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAppRuleStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
