// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// CDPipelineSecretsFindingRisk c d pipeline secrets finding risk
// swagger:model CDPipelineSecretsFindingRisk
type CDPipelineSecretsFindingRisk string

const (

	// CDPipelineSecretsFindingRiskNOKNOWNRISK captures enum value "NO_KNOWN_RISK"
	CDPipelineSecretsFindingRiskNOKNOWNRISK CDPipelineSecretsFindingRisk = "NO_KNOWN_RISK"

	// CDPipelineSecretsFindingRiskRISKIDENTIFIED captures enum value "RISK_IDENTIFIED"
	CDPipelineSecretsFindingRiskRISKIDENTIFIED CDPipelineSecretsFindingRisk = "RISK_IDENTIFIED"
)

// for schema
var cDPipelineSecretsFindingRiskEnum []interface{}

func init() {
	var res []CDPipelineSecretsFindingRisk
	if err := json.Unmarshal([]byte(`["NO_KNOWN_RISK","RISK_IDENTIFIED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		cDPipelineSecretsFindingRiskEnum = append(cDPipelineSecretsFindingRiskEnum, v)
	}
}

func (m CDPipelineSecretsFindingRisk) validateCDPipelineSecretsFindingRiskEnum(path, location string, value CDPipelineSecretsFindingRisk) error {
	if err := validate.Enum(path, location, value, cDPipelineSecretsFindingRiskEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this c d pipeline secrets finding risk
func (m CDPipelineSecretsFindingRisk) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateCDPipelineSecretsFindingRiskEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
