// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteDeployersDeployerIDReader is a Reader for the DeleteDeployersDeployerID structure.
type DeleteDeployersDeployerIDReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDeployersDeployerIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteDeployersDeployerIDNoContent()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDeployersDeployerIDNoContent creates a DeleteDeployersDeployerIDNoContent with default headers values
func NewDeleteDeployersDeployerIDNoContent() *DeleteDeployersDeployerIDNoContent {
	return &DeleteDeployersDeployerIDNoContent{}
}

/*DeleteDeployersDeployerIDNoContent handles this case with default header values.

Success
*/
type DeleteDeployersDeployerIDNoContent struct {
}

func (o *DeleteDeployersDeployerIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /deployers/{deployerId}][%d] deleteDeployersDeployerIdNoContent ", 204)
}

func (o *DeleteDeployersDeployerIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
