// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCdRuleIDConnectionsRuleParams creates a new DeleteCdRuleIDConnectionsRuleParams object
// with the default values initialized.
func NewDeleteCdRuleIDConnectionsRuleParams() *DeleteCdRuleIDConnectionsRuleParams {
	var ()
	return &DeleteCdRuleIDConnectionsRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCdRuleIDConnectionsRuleParamsWithTimeout creates a new DeleteCdRuleIDConnectionsRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCdRuleIDConnectionsRuleParamsWithTimeout(timeout time.Duration) *DeleteCdRuleIDConnectionsRuleParams {
	var ()
	return &DeleteCdRuleIDConnectionsRuleParams{

		timeout: timeout,
	}
}

// NewDeleteCdRuleIDConnectionsRuleParamsWithContext creates a new DeleteCdRuleIDConnectionsRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCdRuleIDConnectionsRuleParamsWithContext(ctx context.Context) *DeleteCdRuleIDConnectionsRuleParams {
	var ()
	return &DeleteCdRuleIDConnectionsRuleParams{

		Context: ctx,
	}
}

// NewDeleteCdRuleIDConnectionsRuleParamsWithHTTPClient creates a new DeleteCdRuleIDConnectionsRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCdRuleIDConnectionsRuleParamsWithHTTPClient(client *http.Client) *DeleteCdRuleIDConnectionsRuleParams {
	var ()
	return &DeleteCdRuleIDConnectionsRuleParams{
		HTTPClient: client,
	}
}

/*DeleteCdRuleIDConnectionsRuleParams contains all the parameters to send to the API endpoint
for the delete cd rule ID connections rule operation typically these are written to a http.Request
*/
type DeleteCdRuleIDConnectionsRuleParams struct {

	/*RuleID
	  ruleId (uid)

	*/
	RuleID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete cd rule ID connections rule params
func (o *DeleteCdRuleIDConnectionsRuleParams) WithTimeout(timeout time.Duration) *DeleteCdRuleIDConnectionsRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cd rule ID connections rule params
func (o *DeleteCdRuleIDConnectionsRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cd rule ID connections rule params
func (o *DeleteCdRuleIDConnectionsRuleParams) WithContext(ctx context.Context) *DeleteCdRuleIDConnectionsRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cd rule ID connections rule params
func (o *DeleteCdRuleIDConnectionsRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cd rule ID connections rule params
func (o *DeleteCdRuleIDConnectionsRuleParams) WithHTTPClient(client *http.Client) *DeleteCdRuleIDConnectionsRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cd rule ID connections rule params
func (o *DeleteCdRuleIDConnectionsRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRuleID adds the ruleID to the delete cd rule ID connections rule params
func (o *DeleteCdRuleIDConnectionsRuleParams) WithRuleID(ruleID strfmt.UUID) *DeleteCdRuleIDConnectionsRuleParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the delete cd rule ID connections rule params
func (o *DeleteCdRuleIDConnectionsRuleParams) SetRuleID(ruleID strfmt.UUID) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCdRuleIDConnectionsRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ruleId
	if err := r.SetPathParam("ruleId", o.RuleID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
