// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteEnvironmentsEnvIDReader is a Reader for the DeleteEnvironmentsEnvID structure.
type DeleteEnvironmentsEnvIDReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteEnvironmentsEnvIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteEnvironmentsEnvIDNoContent()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteEnvironmentEnvIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteEnvironmentsEnvIDNoContent creates a DeleteEnvironmentEnvIDNoContent with default headers values
func NewDeleteEnvironmentsEnvIDNoContent() *DeleteEnvironmentEnvIDNoContent {
	return &DeleteEnvironmentEnvIDNoContent{}
}

/*DeleteEnvironmentEnvIDNoContent handles this case with default header values.

Success
*/
type DeleteEnvironmentEnvIDNoContent struct {
}

func (o *DeleteEnvironmentEnvIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /environments/{envId}][%d] deleteEnvironmentsEnvIdNoContent ", 204)
}

func (o *DeleteEnvironmentEnvIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteEnvironmentEnvIDDefault creates a DeleteEnvironmentEnvIDDefault with default headers values
func NewDeleteEnvironmentEnvIDDefault(code int) *DeleteEnvironmentEnvIDDefault {
	return &DeleteEnvironmentEnvIDDefault{
		_statusCode: code,
	}
}

/*DeleteEnvironmentEnvIDDefault handles this case with default header values.

unknown error
*/
type DeleteEnvironmentEnvIDDefault struct {
	_statusCode int

	Payload *APIResponse
}

// Code gets the status code for the delete environment env ID default response
func (o *DeleteEnvironmentEnvIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteEnvironmentEnvIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /environments/{envId}][%d] DeleteEnvironmentsEnvID default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteEnvironmentEnvIDDefault) GetPayload() *APIResponse {
	return o.Payload
}

func (o *DeleteEnvironmentEnvIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
