// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCdRuleIDServerlessRuleParams creates a new DeleteCdRuleIDServerlessRuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCdRuleIDServerlessRuleParams() *DeleteCdRuleIDServerlessRuleParams {
	return &DeleteCdRuleIDServerlessRuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCdRuleIDServerlessRuleParamsWithTimeout creates a new DeleteCdRuleIDServerlessRuleParams object
// with the ability to set a timeout on a request.
func NewDeleteCdRuleIDServerlessRuleParamsWithTimeout(timeout time.Duration) *DeleteCdRuleIDServerlessRuleParams {
	return &DeleteCdRuleIDServerlessRuleParams{
		timeout: timeout,
	}
}

// NewDeleteCdRuleIDServerlessRuleParamsWithContext creates a new DeleteCdRuleIDServerlessRuleParams object
// with the ability to set a context for a request.
func NewDeleteCdRuleIDServerlessRuleParamsWithContext(ctx context.Context) *DeleteCdRuleIDServerlessRuleParams {
	return &DeleteCdRuleIDServerlessRuleParams{
		Context: ctx,
	}
}

// NewDeleteCdRuleIDServerlessRuleParamsWithHTTPClient creates a new DeleteCdRuleIDServerlessRuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCdRuleIDServerlessRuleParamsWithHTTPClient(client *http.Client) *DeleteCdRuleIDServerlessRuleParams {
	return &DeleteCdRuleIDServerlessRuleParams{
		HTTPClient: client,
	}
}

/* DeleteCdRuleIDServerlessRuleParams contains all the parameters to send to the API endpoint
   for the delete cd rule ID serverless rule operation.

   Typically these are written to a http.Request.
*/
type DeleteCdRuleIDServerlessRuleParams struct {

	/* RuleID.

	   ruleId (uid)

	   Format: uuid
	*/
	RuleID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete cd rule ID serverless rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCdRuleIDServerlessRuleParams) WithDefaults() *DeleteCdRuleIDServerlessRuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete cd rule ID serverless rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCdRuleIDServerlessRuleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete cd rule ID serverless rule params
func (o *DeleteCdRuleIDServerlessRuleParams) WithTimeout(timeout time.Duration) *DeleteCdRuleIDServerlessRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cd rule ID serverless rule params
func (o *DeleteCdRuleIDServerlessRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cd rule ID serverless rule params
func (o *DeleteCdRuleIDServerlessRuleParams) WithContext(ctx context.Context) *DeleteCdRuleIDServerlessRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cd rule ID serverless rule params
func (o *DeleteCdRuleIDServerlessRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cd rule ID serverless rule params
func (o *DeleteCdRuleIDServerlessRuleParams) WithHTTPClient(client *http.Client) *DeleteCdRuleIDServerlessRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cd rule ID serverless rule params
func (o *DeleteCdRuleIDServerlessRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRuleID adds the ruleID to the delete cd rule ID serverless rule params
func (o *DeleteCdRuleIDServerlessRuleParams) WithRuleID(ruleID strfmt.UUID) *DeleteCdRuleIDServerlessRuleParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the delete cd rule ID serverless rule params
func (o *DeleteCdRuleIDServerlessRuleParams) SetRuleID(ruleID strfmt.UUID) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCdRuleIDServerlessRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ruleId
	if err := r.SetPathParam("ruleId", o.RuleID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
