// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteCiPolicyPolicyIDReader is a Reader for the DeleteCiPolicyPolicyID structure.
type DeleteCiPolicyPolicyIDReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCiPolicyPolicyIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteCiPolicyPolicyIDNoContent()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCiPolicyPolicyIDNoContent creates a DeleteCiPolicyPolicyIDNoContent with default headers values
func NewDeleteCiPolicyPolicyIDNoContent() *DeleteCiPolicyPolicyIDNoContent {
	return &DeleteCiPolicyPolicyIDNoContent{}
}

/*DeleteCiPolicyPolicyIDNoContent handles this case with default header values.

Success
*/
type DeleteCiPolicyPolicyIDNoContent struct {
}

func (o *DeleteCiPolicyPolicyIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ciPolicy/{policyId}][%d] deleteCiPolicyPolicyIdNoContent ", 204)
}

func (o *DeleteCiPolicyPolicyIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
