// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTrustedSignersTrustedSignerIDParams creates a new DeleteTrustedSignersTrustedSignerIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTrustedSignersTrustedSignerIDParams() *DeleteTrustedSignersTrustedSignerIDParams {
	return &DeleteTrustedSignersTrustedSignerIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTrustedSignersTrustedSignerIDParamsWithTimeout creates a new DeleteTrustedSignersTrustedSignerIDParams object
// with the ability to set a timeout on a request.
func NewDeleteTrustedSignersTrustedSignerIDParamsWithTimeout(timeout time.Duration) *DeleteTrustedSignersTrustedSignerIDParams {
	return &DeleteTrustedSignersTrustedSignerIDParams{
		timeout: timeout,
	}
}

// NewDeleteTrustedSignersTrustedSignerIDParamsWithContext creates a new DeleteTrustedSignersTrustedSignerIDParams object
// with the ability to set a context for a request.
func NewDeleteTrustedSignersTrustedSignerIDParamsWithContext(ctx context.Context) *DeleteTrustedSignersTrustedSignerIDParams {
	return &DeleteTrustedSignersTrustedSignerIDParams{
		Context: ctx,
	}
}

// NewDeleteTrustedSignersTrustedSignerIDParamsWithHTTPClient creates a new DeleteTrustedSignersTrustedSignerIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTrustedSignersTrustedSignerIDParamsWithHTTPClient(client *http.Client) *DeleteTrustedSignersTrustedSignerIDParams {
	return &DeleteTrustedSignersTrustedSignerIDParams{
		HTTPClient: client,
	}
}

/* DeleteTrustedSignersTrustedSignerIDParams contains all the parameters to send to the API endpoint
   for the delete trusted signers trusted signer ID operation.

   Typically these are written to a http.Request.
*/
type DeleteTrustedSignersTrustedSignerIDParams struct {

	// TrustedSignerID.
	//
	// Format: uuid
	TrustedSignerID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete trusted signers trusted signer ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTrustedSignersTrustedSignerIDParams) WithDefaults() *DeleteTrustedSignersTrustedSignerIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete trusted signers trusted signer ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTrustedSignersTrustedSignerIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete trusted signers trusted signer ID params
func (o *DeleteTrustedSignersTrustedSignerIDParams) WithTimeout(timeout time.Duration) *DeleteTrustedSignersTrustedSignerIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete trusted signers trusted signer ID params
func (o *DeleteTrustedSignersTrustedSignerIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete trusted signers trusted signer ID params
func (o *DeleteTrustedSignersTrustedSignerIDParams) WithContext(ctx context.Context) *DeleteTrustedSignersTrustedSignerIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete trusted signers trusted signer ID params
func (o *DeleteTrustedSignersTrustedSignerIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete trusted signers trusted signer ID params
func (o *DeleteTrustedSignersTrustedSignerIDParams) WithHTTPClient(client *http.Client) *DeleteTrustedSignersTrustedSignerIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete trusted signers trusted signer ID params
func (o *DeleteTrustedSignersTrustedSignerIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTrustedSignerID adds the trustedSignerID to the delete trusted signers trusted signer ID params
func (o *DeleteTrustedSignersTrustedSignerIDParams) WithTrustedSignerID(trustedSignerID strfmt.UUID) *DeleteTrustedSignersTrustedSignerIDParams {
	o.SetTrustedSignerID(trustedSignerID)
	return o
}

// SetTrustedSignerID adds the trustedSignerId to the delete trusted signers trusted signer ID params
func (o *DeleteTrustedSignersTrustedSignerIDParams) SetTrustedSignerID(trustedSignerID strfmt.UUID) {
	o.TrustedSignerID = trustedSignerID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTrustedSignersTrustedSignerIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param trustedSignerId
	if err := r.SetPathParam("trustedSignerId", o.TrustedSignerID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
