// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteEnvironmentEnvIDParams creates a new DeleteEnvironmentsEnvIDParams object
// with the default values initialized.
func NewDeleteEnvironmentEnvIDParams() *DeleteEnvironmentsEnvIDParams {
	var ()
	return &DeleteEnvironmentsEnvIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEnvironmentsEnvIDParamsWithTimeout creates a new DeleteEnvironmentsEnvIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteEnvironmentsEnvIDParamsWithTimeout(timeout time.Duration) *DeleteEnvironmentsEnvIDParams {
	var ()
	return &DeleteEnvironmentsEnvIDParams{

		timeout: timeout,
	}
}

// NewDeleteEnvironmentsEnvIDParamsWithContext creates a new DeleteEnvironmentsEnvIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteEnvironmentsEnvIDParamsWithContext(ctx context.Context) *DeleteEnvironmentsEnvIDParams {
	var ()
	return &DeleteEnvironmentsEnvIDParams{

		Context: ctx,
	}
}

// NewDeleteEnvironmentsEnvIDParamsWithHTTPClient creates a new DeleteEnvironmentsEnvIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteEnvironmentsEnvIDParamsWithHTTPClient(client *http.Client) *DeleteEnvironmentsEnvIDParams {
	var ()
	return &DeleteEnvironmentsEnvIDParams{
		HTTPClient: client,
	}
}

/*DeleteEnvironmentsEnvIDParams contains all the parameters to send to the API endpoint
for the delete environments env ID operation typically these are written to a http.Request
*/
type DeleteEnvironmentsEnvIDParams struct {

	/*EnvID*/
	EnvID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete environments env ID params
func (o *DeleteEnvironmentsEnvIDParams) WithTimeout(timeout time.Duration) *DeleteEnvironmentsEnvIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete environments env ID params
func (o *DeleteEnvironmentsEnvIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete environments env ID params
func (o *DeleteEnvironmentsEnvIDParams) WithContext(ctx context.Context) *DeleteEnvironmentsEnvIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete environments env ID params
func (o *DeleteEnvironmentsEnvIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete environments env ID params
func (o *DeleteEnvironmentsEnvIDParams) WithHTTPClient(client *http.Client) *DeleteEnvironmentsEnvIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete environments env ID params
func (o *DeleteEnvironmentsEnvIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvID adds the envID to the delete environments env ID params
func (o *DeleteEnvironmentsEnvIDParams) WithEnvID(envID strfmt.UUID) *DeleteEnvironmentsEnvIDParams {
	o.SetEnvID(envID)
	return o
}

// SetEnvID adds the envId to the delete environments env ID params
func (o *DeleteEnvironmentsEnvIDParams) SetEnvID(envID strfmt.UUID) {
	o.EnvID = envID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEnvironmentsEnvIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param envId
	if err := r.SetPathParam("envId", o.EnvID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
