// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameReader is a Reader for the GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileName structure.
type GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK creates a GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK with default headers values
func NewGetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK() *GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK {
	return &GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK{}
}

/*GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK handles this case with default header values.

OK
*/
type GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK struct {
	Payload strfmt.UUID
}

func (o *GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK) Error() string {
	return fmt.Sprintf("[GET /cd/podSecurityPolicyProfiles/{podSecurityPolicyProfileName}][%d] getCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK  %+v", 200, o.Payload)
}

func (o *GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK) GetPayload() strfmt.UUID {
	return o.Payload
}

func (o *GetCdPodSecurityPolicyProfilesPodSecurityPolicyProfileNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
