// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCiPolicyParams creates a new GetCiPolicyParams object
// with the default values initialized.
func NewGetCiPolicyParams() *GetCiPolicyParams {

	return &GetCiPolicyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCiPolicyParamsWithTimeout creates a new GetCiPolicyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCiPolicyParamsWithTimeout(timeout time.Duration) *GetCiPolicyParams {

	return &GetCiPolicyParams{

		timeout: timeout,
	}
}

// NewGetCiPolicyParamsWithContext creates a new GetCiPolicyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCiPolicyParamsWithContext(ctx context.Context) *GetCiPolicyParams {

	return &GetCiPolicyParams{

		Context: ctx,
	}
}

// NewGetCiPolicyParamsWithHTTPClient creates a new GetCiPolicyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCiPolicyParamsWithHTTPClient(client *http.Client) *GetCiPolicyParams {

	return &GetCiPolicyParams{
		HTTPClient: client,
	}
}

/*GetCiPolicyParams contains all the parameters to send to the API endpoint
for the get ci policy operation typically these are written to a http.Request
*/
type GetCiPolicyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get ci policy params
func (o *GetCiPolicyParams) WithTimeout(timeout time.Duration) *GetCiPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ci policy params
func (o *GetCiPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ci policy params
func (o *GetCiPolicyParams) WithContext(ctx context.Context) *GetCiPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ci policy params
func (o *GetCiPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ci policy params
func (o *GetCiPolicyParams) WithHTTPClient(client *http.Client) *GetCiPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ci policy params
func (o *GetCiPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCiPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
