// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEnvironmentsEnvIDParams creates a new GetEnvironmentsEnvIDParams object
// with the default values initialized.
func NewGetEnvironmentsEnvIDParams() *GetEnvironmentsEnvIDParams {
	var ()
	return &GetEnvironmentsEnvIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEnvironmentsEnvIDParamsWithTimeout creates a new GetEnvironmentsEnvIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEnvironmentsEnvIDParamsWithTimeout(timeout time.Duration) *GetEnvironmentsEnvIDParams {
	var ()
	return &GetEnvironmentsEnvIDParams{

		timeout: timeout,
	}
}

// NewGetEnvironmentsEnvIDParamsWithContext creates a new GetEnvironmentsEnvIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEnvironmentsEnvIDParamsWithContext(ctx context.Context) *GetEnvironmentsEnvIDParams {
	var ()
	return &GetEnvironmentsEnvIDParams{

		Context: ctx,
	}
}

// NewGetEnvironmentsEnvIDParamsWithHTTPClient creates a new GetEnvironmentsEnvIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEnvironmentsEnvIDParamsWithHTTPClient(client *http.Client) *GetEnvironmentsEnvIDParams {
	var ()
	return &GetEnvironmentsEnvIDParams{
		HTTPClient: client,
	}
}

/*GetEnvironmentsEnvIDParams contains all the parameters to send to the API endpoint
for the get environments env ID operation typically these are written to a http.Request
*/
type GetEnvironmentsEnvIDParams struct {

	/*EnvID*/
	EnvID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get environments env ID params
func (o *GetEnvironmentsEnvIDParams) WithTimeout(timeout time.Duration) *GetEnvironmentsEnvIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get environments env ID params
func (o *GetEnvironmentsEnvIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get environments env ID params
func (o *GetEnvironmentsEnvIDParams) WithContext(ctx context.Context) *GetEnvironmentsEnvIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get environments env ID params
func (o *GetEnvironmentsEnvIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get environments env ID params
func (o *GetEnvironmentsEnvIDParams) WithHTTPClient(client *http.Client) *GetEnvironmentsEnvIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get environments env ID params
func (o *GetEnvironmentsEnvIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvID adds the envID to the get environments env ID params
func (o *GetEnvironmentsEnvIDParams) WithEnvID(envID strfmt.UUID) *GetEnvironmentsEnvIDParams {
	o.SetEnvID(envID)
	return o
}

// SetEnvID adds the envId to the get environments env ID params
func (o *GetEnvironmentsEnvIDParams) SetEnvID(envID strfmt.UUID) {
	o.EnvID = envID
}

// WriteToRequest writes these params to a swagger request
func (o *GetEnvironmentsEnvIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param envId
	if err := r.SetPathParam("envId", o.EnvID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
