// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetCdRuleIDConnectionsRuleReader is a Reader for the GetCdRuleIDConnectionsRule structure.
type GetCdRuleIDConnectionsRuleReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCdRuleIDConnectionsRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCdRuleIDConnectionsRuleOK()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCdRuleIDConnectionsRuleOK creates a GetCdRuleIDConnectionsRuleOK with default headers values
func NewGetCdRuleIDConnectionsRuleOK() *GetCdRuleIDConnectionsRuleOK {
	return &GetCdRuleIDConnectionsRuleOK{}
}

/*GetCdRuleIDConnectionsRuleOK handles this case with default header values.

OK
*/
type GetCdRuleIDConnectionsRuleOK struct {
	Payload *CdConnectionRule
}

func (o *GetCdRuleIDConnectionsRuleOK) Error() string {
	return fmt.Sprintf("[GET /cd/{ruleId}/connectionsRule][%d] getCdRuleIdConnectionsRuleOK  %+v", 200, o.Payload)
}

func (o *GetCdRuleIDConnectionsRuleOK) GetPayload() *CdConnectionRule {
	return o.Payload
}

func (o *GetCdRuleIDConnectionsRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CdConnectionRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
