// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// GetKubernetesClustersKubernetesClusterIDNamespacesReader is a Reader for the GetKubernetesClustersKubernetesClusterIDNamespaces structure.
type GetKubernetesClustersKubernetesClusterIDNamespacesReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKubernetesClustersKubernetesClusterIDNamespacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetKubernetesClustersKubernetesClusterIDNamespacesOK()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetKubernetesClustersKubernetesClusterIDNamespacesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetKubernetesClustersKubernetesClusterIDNamespacesOK creates a GetKubernetesClustersKubernetesClusterIDNamespacesOK with default headers values
func NewGetKubernetesClustersKubernetesClusterIDNamespacesOK() *GetKubernetesClustersKubernetesClusterIDNamespacesOK {
	return &GetKubernetesClustersKubernetesClusterIDNamespacesOK{}
}

/*GetKubernetesClustersKubernetesClusterIDNamespacesOK handles this case with default header values.

success
*/
type GetKubernetesClustersKubernetesClusterIDNamespacesOK struct {
	Payload []*KubernetesNamespaceResponse
}

func (o *GetKubernetesClustersKubernetesClusterIDNamespacesOK) Error() string {
	return fmt.Sprintf("[GET /kubernetesClusters/{kubernetesClusterId}/namespaces][%d] getKubernetesClustersKubernetesClusterIdNamespacesOK  %+v", 200, o.Payload)
}

func (o *GetKubernetesClustersKubernetesClusterIDNamespacesOK) GetPayload() []*KubernetesNamespaceResponse {
	return o.Payload
}

func (o *GetKubernetesClustersKubernetesClusterIDNamespacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetKubernetesClustersKubernetesClusterIDNamespacesDefault creates a GetKubernetesClustersKubernetesClusterIDNamespacesDefault with default headers values
func NewGetKubernetesClustersKubernetesClusterIDNamespacesDefault(code int) *GetKubernetesClustersKubernetesClusterIDNamespacesDefault {
	return &GetKubernetesClustersKubernetesClusterIDNamespacesDefault{
		_statusCode: code,
	}
}

/*GetKubernetesClustersKubernetesClusterIDNamespacesDefault handles this case with default header values.

unknown error
*/
type GetKubernetesClustersKubernetesClusterIDNamespacesDefault struct {
	_statusCode int

	Payload *APIResponse
}

// Code gets the status code for the get kubernetes clusters kubernetes cluster ID namespaces default response
func (o *GetKubernetesClustersKubernetesClusterIDNamespacesDefault) Code() int {
	return o._statusCode
}

func (o *GetKubernetesClustersKubernetesClusterIDNamespacesDefault) Error() string {
	return fmt.Sprintf("[GET /kubernetesClusters/{kubernetesClusterId}/namespaces][%d] GetKubernetesClustersKubernetesClusterIDNamespaces default  %+v", o._statusCode, o.Payload)
}

func (o *GetKubernetesClustersKubernetesClusterIDNamespacesDefault) GetPayload() *APIResponse {
	return o.Payload
}

func (o *GetKubernetesClustersKubernetesClusterIDNamespacesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
