// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// InternalRegistryParameters internal registry information
// swagger:model internalRegistryParameters
type InternalRegistryParameters struct {

	// when internal registry enabled, specify the registry URL
	InternalRegistry string `json:"internalRegistry,omitempty"`

	// indicates whether internal registry is enabled
	InternalRegistryEnabled *bool `json:"internalRegistryEnabled,omitempty"`
}

// Validate validates this internal registry parameters
func (m *InternalRegistryParameters) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InternalRegistryParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalRegistryParameters) UnmarshalBinary(b []byte) error {
	var res InternalRegistryParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
