// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// IstioInstallationParameters istio related information
// swagger:model IstioInstallationParameters
type IstioInstallationParameters struct {

	// indicates whether Istio is already installed on this cluster (which means SecureCn should not install it)
	IsIstioAlreadyInstalled *bool `json:"isIstioAlreadyInstalled,omitempty"`

	// when istio already installed, choose the version from supported istio versions list: /istio/supportedVersions
	IstioVersion string `json:"istioVersion,omitempty"`
}

// Validate validates this istio installation parameters
func (m *IstioInstallationParameters) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IstioInstallationParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IstioInstallationParameters) UnmarshalBinary(b []byte) error {
	var res IstioInstallationParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
