// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PodValidation pod validation
// swagger:model PodValidation
type PodValidation struct {

	// pod security policy
	PodSecurityPolicy *PodSecurityPolicyValidation `json:"podSecurityPolicy,omitempty"`

	// vulnerability
	Vulnerability *VulnerabilityValidation `json:"vulnerability,omitempty"`
}

// Validate validates this pod validation
func (m *PodValidation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePodSecurityPolicy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVulnerability(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PodValidation) validatePodSecurityPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.PodSecurityPolicy) { // not required
		return nil
	}

	if m.PodSecurityPolicy != nil {
		if err := m.PodSecurityPolicy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("podSecurityPolicy")
			}
			return err
		}
	}

	return nil
}

func (m *PodValidation) validateVulnerability(formats strfmt.Registry) error {

	if swag.IsZero(m.Vulnerability) { // not required
		return nil
	}

	if m.Vulnerability != nil {
		if err := m.Vulnerability.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vulnerability")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PodValidation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PodValidation) UnmarshalBinary(b []byte) error {
	var res PodValidation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
