// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// PostCiPolicyReader is a Reader for the PostCiPolicy structure.
type PostCiPolicyReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCiPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostCiPolicyCreated()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostCiPolicyUnauthorized()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostCiPolicyCreated creates a PostCiPolicyCreated with default headers values
func NewPostCiPolicyCreated() *PostCiPolicyCreated {
	return &PostCiPolicyCreated{}
}

/*PostCiPolicyCreated handles this case with default header values.

Added
*/
type PostCiPolicyCreated struct {
	Payload *CiPolicy
}

func (o *PostCiPolicyCreated) Error() string {
	return fmt.Sprintf("[POST /ciPolicy][%d] postCiPolicyCreated  %+v", 201, o.Payload)
}

func (o *PostCiPolicyCreated) GetPayload() *CiPolicy {
	return o.Payload
}

func (o *PostCiPolicyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CiPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCiPolicyUnauthorized creates a PostCiPolicyUnauthorized with default headers values
func NewPostCiPolicyUnauthorized() *PostCiPolicyUnauthorized {
	return &PostCiPolicyUnauthorized{}
}

/*PostCiPolicyUnauthorized handles this case with default header values.

Unauthorized.
*/
type PostCiPolicyUnauthorized struct {
}

func (o *PostCiPolicyUnauthorized) Error() string {
	return fmt.Sprintf("[POST /ciPolicy][%d] postCiPolicyUnauthorized ", 401)
}

func (o *PostCiPolicyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
