// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

)

// NewPostCdServerlessRuleParams creates a new PostCdServerlessRuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCdServerlessRuleParams() *PostCdServerlessRuleParams {
	return &PostCdServerlessRuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCdServerlessRuleParamsWithTimeout creates a new PostCdServerlessRuleParams object
// with the ability to set a timeout on a request.
func NewPostCdServerlessRuleParamsWithTimeout(timeout time.Duration) *PostCdServerlessRuleParams {
	return &PostCdServerlessRuleParams{
		timeout: timeout,
	}
}

// NewPostCdServerlessRuleParamsWithContext creates a new PostCdServerlessRuleParams object
// with the ability to set a context for a request.
func NewPostCdServerlessRuleParamsWithContext(ctx context.Context) *PostCdServerlessRuleParams {
	return &PostCdServerlessRuleParams{
		Context: ctx,
	}
}

// NewPostCdServerlessRuleParamsWithHTTPClient creates a new PostCdServerlessRuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCdServerlessRuleParamsWithHTTPClient(client *http.Client) *PostCdServerlessRuleParams {
	return &PostCdServerlessRuleParams{
		HTTPClient: client,
	}
}

/* PostCdServerlessRuleParams contains all the parameters to send to the API endpoint
   for the post cd serverless rule operation.

   Typically these are written to a http.Request.
*/
type PostCdServerlessRuleParams struct {

	// Body.
	Body *CdServerlessRule

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post cd serverless rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCdServerlessRuleParams) WithDefaults() *PostCdServerlessRuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post cd serverless rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCdServerlessRuleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post cd serverless rule params
func (o *PostCdServerlessRuleParams) WithTimeout(timeout time.Duration) *PostCdServerlessRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post cd serverless rule params
func (o *PostCdServerlessRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post cd serverless rule params
func (o *PostCdServerlessRuleParams) WithContext(ctx context.Context) *PostCdServerlessRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post cd serverless rule params
func (o *PostCdServerlessRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post cd serverless rule params
func (o *PostCdServerlessRuleParams) WithHTTPClient(client *http.Client) *PostCdServerlessRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post cd serverless rule params
func (o *PostCdServerlessRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post cd serverless rule params
func (o *PostCdServerlessRuleParams) WithBody(body *CdServerlessRule) *PostCdServerlessRuleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post cd serverless rule params
func (o *PostCdServerlessRuleParams) SetBody(body *CdServerlessRule) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostCdServerlessRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
