// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostCdServerlessRuleReader is a Reader for the PostCdServerlessRule structure.
type PostCdServerlessRuleReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCdServerlessRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostCdServerlessRuleCreated()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostCdServerlessRuleCreated creates a PostCdServerlessRuleCreated with default headers values
func NewPostCdServerlessRuleCreated() *PostCdServerlessRuleCreated {
	return &PostCdServerlessRuleCreated{}
}

/* PostCdServerlessRuleCreated describes a response with status code 201, with default header values.

created.
*/
type PostCdServerlessRuleCreated struct {
	Payload *CdServerlessRule
}

func (o *PostCdServerlessRuleCreated) Error() string {
	return fmt.Sprintf("[POST /cd/serverlessRule][%d] postCdServerlessRuleCreated  %+v", 201, o.Payload)
}
func (o *PostCdServerlessRuleCreated) GetPayload() *CdServerlessRule {
	return o.Payload
}

func (o *PostCdServerlessRuleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CdServerlessRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
