// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostDeployersParams creates a new PostDeployersParams object
// with the default values initialized.
func NewPostDeployersParams() *PostDeployersParams {
	var ()
	return &PostDeployersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostDeployersParamsWithTimeout creates a new PostDeployersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostDeployersParamsWithTimeout(timeout time.Duration) *PostDeployersParams {
	var ()
	return &PostDeployersParams{

		timeout: timeout,
	}
}

// NewPostDeployersParamsWithContext creates a new PostDeployersParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostDeployersParamsWithContext(ctx context.Context) *PostDeployersParams {
	var ()
	return &PostDeployersParams{

		Context: ctx,
	}
}

// NewPostDeployersParamsWithHTTPClient creates a new PostDeployersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostDeployersParamsWithHTTPClient(client *http.Client) *PostDeployersParams {
	var ()
	return &PostDeployersParams{
		HTTPClient: client,
	}
}

/*PostDeployersParams contains all the parameters to send to the API endpoint
for the post deployers operation typically these are written to a http.Request
*/
type PostDeployersParams struct {

	/*Body*/
	Body Deployer

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post deployers params
func (o *PostDeployersParams) WithTimeout(timeout time.Duration) *PostDeployersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post deployers params
func (o *PostDeployersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post deployers params
func (o *PostDeployersParams) WithContext(ctx context.Context) *PostDeployersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post deployers params
func (o *PostDeployersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post deployers params
func (o *PostDeployersParams) WithHTTPClient(client *http.Client) *PostDeployersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post deployers params
func (o *PostDeployersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post deployers params
func (o *PostDeployersParams) WithBody(body Deployer) *PostDeployersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post deployers params
func (o *PostDeployersParams) SetBody(body Deployer) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostDeployersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
