// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutCdRuleIDServerlessRuleReader is a Reader for the PutCdRuleIDServerlessRule structure.
type PutCdRuleIDServerlessRuleReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutCdRuleIDServerlessRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutCdRuleIDServerlessRuleOK()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutCdRuleIDServerlessRuleOK creates a PutCdRuleIDServerlessRuleOK with default headers values
func NewPutCdRuleIDServerlessRuleOK() *PutCdRuleIDServerlessRuleOK {
	return &PutCdRuleIDServerlessRuleOK{}
}

/* PutCdRuleIDServerlessRuleOK describes a response with status code 200, with default header values.

updated
*/
type PutCdRuleIDServerlessRuleOK struct {
	Payload *CdServerlessRule
}

func (o *PutCdRuleIDServerlessRuleOK) Error() string {
	return fmt.Sprintf("[PUT /cd/{ruleId}/serverlessRule][%d] putCdRuleIdServerlessRuleOK  %+v", 200, o.Payload)
}
func (o *PutCdRuleIDServerlessRuleOK) GetPayload() *CdServerlessRule {
	return o.Payload
}

func (o *PutCdRuleIDServerlessRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CdServerlessRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
