// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
)

// PutCdPolicyPolicyIDReader is a Reader for the PutCdPolicyPolicyID structure.
type PutCdPolicyPolicyIDReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutCdPolicyPolicyIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutCdPolicyPolicyIDOK()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutCdPolicyPolicyIDOK creates a PutCdPolicyPolicyIDOK with default headers values
func NewPutCdPolicyPolicyIDOK() *PutCdPolicyPolicyIDOK {
	return &PutCdPolicyPolicyIDOK{}
}

/*PutCdPolicyPolicyIDOK handles this case with default header values.

Success
*/
type PutCdPolicyPolicyIDOK struct {
	Payload *CdPolicy
}

func (o *PutCdPolicyPolicyIDOK) Error() string {
	return fmt.Sprintf("[PUT /cdPolicy/{policyId}][%d] putCdPolicyPolicyIdOK  %+v", 200, o.Payload)
}

func (o *PutCdPolicyPolicyIDOK) GetPayload() *CdPolicy {
	return o.Payload
}

func (o *PutCdPolicyPolicyIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CdPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
