// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutTrustedSignersTrustedSignerIDReader is a Reader for the PutTrustedSignersTrustedSignerID structure.
type PutTrustedSignersTrustedSignerIDReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutTrustedSignersTrustedSignerIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPutTrustedSignersTrustedSignerIDCreated()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutTrustedSignersTrustedSignerIDCreated creates a PutTrustedSignersTrustedSignerIDCreated with default headers values
func NewPutTrustedSignersTrustedSignerIDCreated() *PutTrustedSignersTrustedSignerIDCreated {
	return &PutTrustedSignersTrustedSignerIDCreated{}
}

/* PutTrustedSignersTrustedSignerIDCreated describes a response with status code 201, with default header values.

Edited
*/
type PutTrustedSignersTrustedSignerIDCreated struct {
}

func (o *PutTrustedSignersTrustedSignerIDCreated) Error() string {
	return fmt.Sprintf("[PUT /trustedSigners/{trustedSignerId}][%d] putTrustedSignersTrustedSignerIdCreated ", 201)
}

func (o *PutTrustedSignersTrustedSignerIDCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
