// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutCdRuleIDConnectionsRuleReader is a Reader for the PutCdRuleIDConnectionsRule structure.
type PutCdRuleIDConnectionsRuleReader struct {
	Formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutCdRuleIDConnectionsRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutCdRuleIDConnectionsRuleOK()
		if err := result.readResponse(response, consumer, o.Formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutCdRuleIDConnectionsRuleOK creates a PutCdRuleIDConnectionsRuleOK with default headers values
func NewPutCdRuleIDConnectionsRuleOK() *PutCdRuleIDConnectionsRuleOK {
	return &PutCdRuleIDConnectionsRuleOK{}
}

/*PutCdRuleIDConnectionsRuleOK handles this case with default header values.

updated
*/
type PutCdRuleIDConnectionsRuleOK struct {
	Payload *CdConnectionRule
}

func (o *PutCdRuleIDConnectionsRuleOK) Error() string {
	return fmt.Sprintf("[PUT /cd/{ruleId}/connectionsRule][%d] putCdRuleIdConnectionsRuleOK  %+v", 200, o.Payload)
}

func (o *PutCdRuleIDConnectionsRuleOK) GetPayload() *CdConnectionRule {
	return o.Payload
}

func (o *PutCdRuleIDConnectionsRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CdConnectionRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
