// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServerlessRuleScope serverless rule scope
//
// swagger:model ServerlessRuleScope
type ServerlessRuleScope struct {

	// cloud account name
	// Required: true
	CloudAccount *string `json:"cloudAccount"`

	// empty for any
	Regions []string `json:"regions"`
}

// Validate validates this serverless rule scope
func (m *ServerlessRuleScope) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCloudAccount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServerlessRuleScope) validateCloudAccount(formats strfmt.Registry) error {

	if err := validate.Required("cloudAccount", "body", m.CloudAccount); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this serverless rule scope based on context it is used
func (m *ServerlessRuleScope) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerlessRuleScope) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerlessRuleScope) UnmarshalBinary(b []byte) error {
	var res ServerlessRuleScope
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
