// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SidecarsResource sidecars resource
// swagger:model sidecarsResource
type SidecarsResource struct {

	// proxy init limits Cpu
	// Minimum: 1
	ProxyInitLimitsCPU int64 `json:"proxyInitLimitsCpu,omitempty"`

	// proxy init limits memory
	// Minimum: 1
	ProxyInitLimitsMemory int64 `json:"proxyInitLimitsMemory,omitempty"`

	// proxy init requests Cpu
	// Minimum: 1
	ProxyInitRequestsCPU int64 `json:"proxyInitRequestsCpu,omitempty"`

	// proxy init requests memory
	// Minimum: 1
	ProxyInitRequestsMemory int64 `json:"proxyInitRequestsMemory,omitempty"`

	// proxy limits Cpu
	// Minimum: 1
	ProxyLimitsCPU int64 `json:"proxyLimitsCpu,omitempty"`

	// proxy limits memory
	// Minimum: 1
	ProxyLimitsMemory int64 `json:"proxyLimitsMemory,omitempty"`

	// proxy request Cpu
	// Minimum: 1
	ProxyRequestCPU int64 `json:"proxyRequestCpu,omitempty"`

	// proxy request memory
	// Minimum: 1
	ProxyRequestMemory int64 `json:"proxyRequestMemory,omitempty"`
}

// Validate validates this sidecars resource
func (m *SidecarsResource) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProxyInitLimitsCPU(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProxyInitLimitsMemory(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProxyInitRequestsCPU(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProxyInitRequestsMemory(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProxyLimitsCPU(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProxyLimitsMemory(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProxyRequestCPU(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProxyRequestMemory(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SidecarsResource) validateProxyInitLimitsCPU(formats strfmt.Registry) error {

	if swag.IsZero(m.ProxyInitLimitsCPU) { // not required
		return nil
	}

	if err := validate.MinimumInt("proxyInitLimitsCpu", "body", int64(m.ProxyInitLimitsCPU), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *SidecarsResource) validateProxyInitLimitsMemory(formats strfmt.Registry) error {

	if swag.IsZero(m.ProxyInitLimitsMemory) { // not required
		return nil
	}

	if err := validate.MinimumInt("proxyInitLimitsMemory", "body", int64(m.ProxyInitLimitsMemory), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *SidecarsResource) validateProxyInitRequestsCPU(formats strfmt.Registry) error {

	if swag.IsZero(m.ProxyInitRequestsCPU) { // not required
		return nil
	}

	if err := validate.MinimumInt("proxyInitRequestsCpu", "body", int64(m.ProxyInitRequestsCPU), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *SidecarsResource) validateProxyInitRequestsMemory(formats strfmt.Registry) error {

	if swag.IsZero(m.ProxyInitRequestsMemory) { // not required
		return nil
	}

	if err := validate.MinimumInt("proxyInitRequestsMemory", "body", int64(m.ProxyInitRequestsMemory), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *SidecarsResource) validateProxyLimitsCPU(formats strfmt.Registry) error {

	if swag.IsZero(m.ProxyLimitsCPU) { // not required
		return nil
	}

	if err := validate.MinimumInt("proxyLimitsCpu", "body", int64(m.ProxyLimitsCPU), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *SidecarsResource) validateProxyLimitsMemory(formats strfmt.Registry) error {

	if swag.IsZero(m.ProxyLimitsMemory) { // not required
		return nil
	}

	if err := validate.MinimumInt("proxyLimitsMemory", "body", int64(m.ProxyLimitsMemory), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *SidecarsResource) validateProxyRequestCPU(formats strfmt.Registry) error {

	if swag.IsZero(m.ProxyRequestCPU) { // not required
		return nil
	}

	if err := validate.MinimumInt("proxyRequestCpu", "body", int64(m.ProxyRequestCPU), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *SidecarsResource) validateProxyRequestMemory(formats strfmt.Registry) error {

	if swag.IsZero(m.ProxyRequestMemory) { // not required
		return nil
	}

	if err := validate.MinimumInt("proxyRequestMemory", "body", int64(m.ProxyRequestMemory), 1, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SidecarsResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SidecarsResource) UnmarshalBinary(b []byte) error {
	var res SidecarsResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
