// Code generated by go-swagger; DO NOT EDIT.

package model

import "github.com/go-openapi/swag"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// SidecarsResource sidecars resource
// swagger:model sidecarsResource
type SidecarsResource struct {

	// proxy init limits Cpu
	// Minimum: 1
	ProxyInitLimitsCPU string `json:"proxyInitLimitsCpu,omitempty"`

	// proxy init limits memory
	// Minimum: 1
	ProxyInitLimitsMemory string `json:"proxyInitLimitsMemory,omitempty"`

	// proxy init requests Cpu
	// Minimum: 1
	ProxyInitRequestsCPU string `json:"proxyInitRequestsCpu,omitempty"`

	// proxy init requests memory
	// Minimum: 1
	ProxyInitRequestsMemory string `json:"proxyInitRequestsMemory,omitempty"`

	// proxy limits Cpu
	// Minimum: 1
	ProxyLimitsCPU string `json:"proxyLimitsCpu,omitempty"`

	// proxy limits memory
	// Minimum: 1
	ProxyLimitsMemory string `json:"proxyLimitsMemory,omitempty"`

	// proxy request Cpu
	// Minimum: 1
	ProxyRequestCPU string `json:"proxyRequestCpu,omitempty"`

	// proxy request memory
	// Minimum: 1
	ProxyRequestMemory string `json:"proxyRequestMemory,omitempty"`
}

// MarshalBinary interface implementation
func (m *SidecarsResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SidecarsResource) UnmarshalBinary(b []byte) error {
	var res SidecarsResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
