// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TracingSupportSettings tracing support settings
// swagger:model TracingSupportSettings
type TracingSupportSettings struct {

	// indicates whether to install tracing support, enable for apiSecuroty accounts
	InstallTracingSupport *bool `json:"installTracingSupport,omitempty"`

	// indicates whether spec reconstrutor is enabled. available when installTracingSupport = true
	SpecReconstructorEnabled *bool `json:"specReconstructorEnabled,omitempty"`

	// indicates whether trace Analyzer is enabled. available when installTracingSupport = true
	TraceAnalyzerEnabled *bool `json:"traceAnalyzerEnabled,omitempty"`
}

// Validate validates this tracing support settings
func (m *TracingSupportSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TracingSupportSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TracingSupportSettings) UnmarshalBinary(b []byte) error {
	var res TracingSupportSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
